window.jQuery = window.$ = require('jquery');
window.ymaps = require('ymaps').default;
require('jquery-validation');
require('./modal');
window.angular = require('angular');
require('angular-route');
require('@uirouter/angularjs');
require('jpkleemans-angular-validate');
require('ngStorage');
require('angular-base64');
require('magnific-popup');
